### ISSUE TITLE
polybar-msg is not versionned in this repository

### ISSUE THREAD

**Issue by zopieux** [vincentbernat/i3wm-configuration#2]
Hello,

Thanks for open-sourcing your setup, which I find particularly elegant and well tough-out. I've noticed the `.local/bin/polybar-msg cmd` binary used in https://github.com/vincentbernat/i3wm-configuration/blob/79ca480eeb7ef4ba96a3806f4008a07c35410482/dotfiles/systemd/polybar.service (to send "quit") is not versioned here, making for a slightly broken setup if we were to use this as-is.

Could you add that script to the repo? Thanks!

**Comment by vincentbernat** [comment]
It's not a script, this is my local copy of polybar. When I am not using the upstream version as is, I put the result in `~/.local/bin`. That's also the case for Dunst.

**Comment by zopieux** [comment]
Thanks for the update!
