### ISSUE TITLE
Q: how do you launch your xsession?

### ISSUE THREAD

**Issue by laur89** [vincentbernat/i3wm-configuration#3]
Sorry, not an issue but a question if you don't mind looking at.
How do you go about loading your [xsession](https://github.com/vincentbernat/i3wm-configuration/blob/master/dotfiles/xsession)?

_Btw thanks for your excellent [blog post](https://vincent.bernat.ch/en/blog/2021-i3-window-manager), it helped me overcome issue of notifications nor automatic gnome-keyring unlocking not working._

**Comment by vincentbernat** [comment]
I am using this: https://vincent.bernat.ch/en/blog/2021-startx-systemd and `~/.xsession` is a symlink to `.config/i3/dotfiles/xsession`.

**Comment by laur89** [comment]
Ah so on your system `startx` automatically picks up `~/.xsession` without explicitly passing it as input param.
So starting from say `~/.profile` via `exec startx ~/.xsession` should still do the trick.

**Comment by vincentbernat** [comment]
Yes, `startx` runs `xinit` which runs `.xsession` (the manual page says `.xinitrc`, so it may be dependent on the distribution, I am running Debian). Also, if the user has no session registered into its profile (in `.dmrc`), the login managers are also using `.xsession` (or maybe `.xinitrc`).

**Comment by laur89** [comment]
I'm running Debian testing, and looks like if both .xinitrc & .xsession are present in homedir, then `startx` by default executes the former still.

Anyway, thanks again for you blog and input, my system is now in a _much_ better place.
